INSERT INTO Artis (id_artis, nama, negara_asal, biografi) VALUES
(1, 'Lunar Echo', 'Indonesia', 'Grup elektronik-pop asal Jakarta yang dikenal dengan beat dreamy dan lirik puitis.'),
(2, 'NeonDrift', 'Amerika Serikat', 'DJ dan produser musik EDM dari LA dengan gaya futuristik.'),
(3, 'Soulstice', 'Inggris', 'Band indie soul dengan nuansa lo-fi dan vokal mellow.'),
(4, 'Aurora Haze', 'Australia', 'Penyanyi solo yang memadukan pop dan ambient dengan lirik introspektif.'),
(5, 'Funkzilla', 'Brazil', 'Band funk rock yang energik dan sering tampil dengan koreografi unik.'),
(6, 'Midnight Mango', 'Indonesia', 'Duo elektronik-akustik dari Bandung yang viral di TikTok.'),
(7, 'TrapKoala', 'Korea Selatan', 'Rapper Gen Z dengan trap beat yang eksperimental.'),
(8, 'ZynthWave', 'Jerman', 'Grup synthwave yang mengusung nuansa retro 80an.'),
(9, 'Cloudberry', 'Swedia', 'Solois bergenre dream pop dengan suara lembut dan estetika visual artsy.'),
(10, 'KopiLoops', 'Indonesia', 'Produser lo-fi beats yang sering muncul di playlist belajar dan ngopi.'),
(11, 'RAVE++', 'Belanda', 'Grup tekno underground yang dikenal di festival rave Eropa.'),
(12, 'ChocoTrap', 'Jepang', 'Trio hyperpop dengan visual kawaii dan musik over-the-top.'),
(13, 'Serenade.exe', 'Singapura', 'Duo elektronik dengan sentuhan cyberpunk dan glitch.'),
(14, 'NusaNova', 'Indonesia', 'Grup world music dengan elemen etnik Bali dan jazz modern.'),
(15, 'Glitchbloom', 'Prancis', 'Band rock elektronik dengan vokal auto-tune artistik.'),
(16, 'PixelMuse', 'Kanada', 'Produser yang memadukan chip tune dan musik klasik.'),
(17, 'RimbaNoise', 'Indonesia', 'Grup eksperimental yang menggunakan suara hutan dan suara manusia.'),
(18, 'VelvetFire', 'Italia', 'Vokalis pop-rock dengan performa panggung teatrikal.'),
(19, 'NeoRasa', 'Indonesia', 'Kolaborasi musisi jazz dan RnB dengan gaya Gen Z.'),
(20, 'EchoRush', 'India', 'Band alternative rock dengan elemen sitar dan synth.');
